### ISSUE TITLE
IndexOutOfRangeException occurred in Readbytes

### ISSUE THREAD

**Issue by Norgerman** [StormHub/NetUV#50]
Exception detail
```
System.IndexOutOfRangeException occurred
  HResult=0x80131508
  Message=ReaderIndex: 826 (expected: 0 <= readerIndex <= writerIndex(413)
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at NetUV.Core.Buffers.AbstractArrayBuffer`1.SetReaderIndex(Int32 readerIndex)
   at NetUV.Core.Buffers.ReadableBuffer.ReadBytes(Byte[] destination, Int32 length)
   at Shark.Internal.UvClient.OnAccept(Tcp tcp, ReadableBuffer readableBuffer) in C:\Users\XXX\Documents\Visual Studio 2017\Projects\Shark\Shark\Internal\UvClient.cs:line 103
   at NetUV.Core.Handles.Tcp.<>c__DisplayClass8_0.<OnRead>b__0(StreamHandle stream, ReadableBuffer buffer)
   at NetUV.Core.Channels.StreamConsumer`1.Consume(T stream, IStreamReadCompletion readCompletion)
```

**Comment by doruu12** [comment]
Minor bug in the updating reader position
https://github.com/StormHub/NetUV/pull/51

**Comment by StormHub** [comment]
#52
